services:
  db:
    image: postgres:15-alpine
    container_name: iu-webforum-db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgrespassword
      POSTGRES_DB: webforum
    ports:
      - "5432:5432"
    volumes:
      - ./postgres-data:/var/lib/postgresql/data